### ISSUE TITLE
Two instance of contextmenu

### ISSUE THREAD

**Issue by lenincasco** [isaacplmann/angular2-contextmenu#13]
Hi, Is it possible to use two contextmenu's instances in the same component with a different template?

Thanks

**Comment by isaacplmann** [comment]
I don't think so in the current version. I'll be putting in a feature on
Monday that should do the trick though.

**Comment by isaacplmann** [comment]
There is now (in 0.3.0) a `[visible]` input on `contextMenuItem`, so you can make context menu items only show for certain types of items.  You won't have two different context menu instances, but you can achieve the same functionality by hiding and showing the menu items.  Reopen if this doesn't satisfy your requirements.

**Comment by lenincasco** [comment]
Thanks, I'm going to check that, I'll let you know

**Comment by lenincasco** [comment]
Thanks, I managed to do what needed with the new functionality [visible]

**Comment by isaacplmann** [comment]
In version 0.4.0, you can now do this explicitly by using the `[contextMenu]` directive to wire up the context menu, or by referencing the context menu component you want to open in the `contextMenu` property in `this.contextMenuService.show.next({ contextMenu: this.myContextMenu, event, item })`
