### ISSUE TITLE
Configurable "left" click scenario

### ISSUE THREAD

**Issue by jvanderbiest** [isaacplmann/angular2-contextmenu#14]
I have a scenario where I need to show a context menu on left click (on a button) instead of right click. The behaviour should be exactly the same as it is now. Can you implement this?

Would love to create a pull request for this but a clean fork isn't compiling well :-(

**Comment by isaacplmann** [comment]
I don't think you need to modify the library at all.

In your component, just do something like this:

```js
import { ContextMenuService } from 'angular2-contextmenu';

@Component({
  template: '<ul><li *ngFor="let item of items" (click)="showContextMenu">{{item.name}}</li></ul>'
})
export class MyContextMenuClass {
  public items = [
      { name: 'John', otherProperty: 'Foo' },
      { name: 'Joe', otherProperty: 'Bar' }
  };

  constructor(private contextMenuService: ContextMenuService) {}

  public showContextMenu($event: MouseEvent, item: any): void {
    this.contextMenuService.show.next({ event: $event, item: item });
    $event.preventDefault();
  }
}
```

I just changed the template to fire `showContextMenu` when a `click` event happens instead of a `contextmenu` event.

**Comment by isaacplmann** [comment]
Closing.  Reopen if this method doesn't work.

**Comment by jvanderbiest** [comment]
thanks, works great. 🚀

**Comment by jredd** [comment]
worked great for me as well! Had fiddle with it to work properly since I wasn't creating it off of a loop
