### ISSUE TITLE
Keep imperative approach for defining menu items?

### ISSUE THREAD

**Issue by rsinger86** [isaacplmann/angular2-contextmenu#15]
hi, thanks for making this component - it's very useful! I just had a suggestion...

In my app, I want to re-use the same context menu in many different components. With the new declarative approach, there is no easy way for me to duplicate these menu items across multiple components, because of how the ContextMenuComponent uses ContentChildren, which hardcodes the item definitions into templates. But with the imperative approach, it's easy to define these items in a TypeScript module that I import various places.

**Comment by isaacplmann** [comment]
I think I can help you come up with a way to use the declarative approach.
I'll send some ideas on Monday.
However, if none of the ideas work for you, I'll keep the imperative
approach.

**Comment by isaacplmann** [comment]
Here's my proposal:
```html
<ul>
    <li *ngFor="item in items" (contextmenu)="onContextMenu($event, item)">Right Click: {{item.name}}</li>
</ul>
<context-menu>
  <template *ngFor="let action of contextMenuActions" contextMenuItem let-item
    [visible]="action.isVisible()" [enabled]="action.isEnabled()"
    (execute)="action.execute($event.item)">
    {{ action.html(item) }}
  </template>
</context-menu>
```

```js
import { ContextMenuService } from 'angular2-contextmenu';

@Component({
  ...
})
export class MyContextMenuClass {
  public items = [
      { name: 'John', otherProperty: 'Foo' },
      { name: 'Joe', otherProperty: 'Bar' }
  };
  public selectedItem: any;
  public contextMenuActions = [
        {
          html: (item) => `Say hi!`,
          click: (item) => alert('Hi, ' + item.name)
          enabled: () => true,
          visible: () => this.selectedItem && this.selectedItem.type === 'type1',
        },
        {
          html: (item) => `Something else`,
          click: (item) => alert('Or not...'),
          enabled: () => false,
          visible: () => this.selectedItem && this.selectedItem.type === 'type1',
        },
      ];

  constructor(private contextMenuService: ContextMenuService) {}

  public onContextMenu($event: MouseEvent, item: any): void {
    this.selectedItem = item;
    this.contextMenuService.show.next({ event: $event, item });
    $event.preventDefault();
  }
}
```

Will this work for you?

You can still update the `contextMenuActions` property by importing from a static file or using a service.

If this doesn't work, I can include the `*ngFor` logic into the library and expose an `[actions]` property on the `<context-menu>` tag.

**Comment by isaacplmann** [comment]
What do you think of my proposed declarative approach?  Does it satisfy your needs?

**Comment by spanda90** [comment]
Instead of contextmenuactions if I want to iterate based on item.actions.. can I do that ?

**Comment by spanda90** [comment]
if yes can you provide an example

**Comment by isaacplmann** [comment]
The imperative approach is no longer supported in version 1.x (renamed to [ngx-contextmenu](https://github.com/isaacplmann/ngx-contextmenu))

**Comment by isaacplmann** [comment]
This issue was moved to isaacplmann/ngx-contextmenu#7
