### ISSUE TITLE
Bootstrap 4 config

### ISSUE THREAD

**Issue by k-schneider** [isaacplmann/angular2-contextmenu#17]
Hi,

Just wondering if instead of having to put [useBootstrap4] on every context menu if it would be better to configure the module at time of import ([using forRoot](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root)).  I'd rather configure this setting globally vs for every menu.

Thanks

**Comment by isaacplmann** [comment]
That's a good idea. I'll see what I can do.

**Comment by isaacplmann** [comment]
This is implemented in version 0.5.1.  Enjoy!

    @NgModule({
      providers: [
        ContentMenuModule.forRoot({
          useBootstrap4: true,
        }),
      ],
    })
    export class AppModule {}

**Comment by k-schneider** [comment]
Awesome - nice work!
