### ISSUE TITLE
Fix typo in README.md

### ISSUE THREAD

**Issue by balde73** [isaacplmann/angular2-contextmenu#19]
The [README.md](https://github.com/isaacplmann/angular2-contextmenu/blob/master/README.md) file show the following code:
```
public items = [
      { name: 'John', otherProperty: 'Foo' },
      { name: 'Joe', otherProperty: 'Bar' }
};
```
instead of:
```
public items = [
      { name: 'John', otherProperty: 'Foo' },
      { name: 'Joe', otherProperty: 'Bar' }
];
```
This is repeated 3times.
Please replace ```};``` with ```];``` on:
- line 43
- line 119
- line 230

**Comment by isaacplmann** [comment]
Fixed.  Thanks!
