### ISSUE TITLE
Handle 'this' in visible/enabled functions

### ISSUE THREAD

**Issue by JulienNexonia** [isaacplmann/angular2-contextmenu#20]
I am currently using the visible feature to see/hide an option in the menu.
The corresponding method need a little bit more logic than just checking the type of the option.
I need a reference to the component through 'this'.

For example, let's see the following template for the context menu :

```
<context-menu #withFunctions>
  <template contextMenuItem [visible]="myMethod" (execute)="showMessage('Hi, ' + $event.item.name)">
    Say hi! (visible for Joe)
  </template>
</context-menu>
```
_myMethod_ reference to the following snippet in the component : 

```
  type = 'typeA';
  minValue = '10';
...
  public myMethod(item: any): boolean {
    //return item.name === 'John';
    return item.data.type === this.type && item.data.value > this.minValue;
  }
```

As minValue can evolve during the process, I would like to be able to use this as a reference to the component.  Currently this is 'undefined' and _myMethod_ will not answer my needs.

Do you have any idea how to perform such a case ?
Thanks in advance.

Regards,
Julien

**Comment by isaacplmann** [comment]
You'll need to pass in a function that has `this` bound to it.

```js
myBoundMethod = this.myMethod.bind(this)
// or
public myBoundMethod(): (item:any) => boolean {
  return this.myMethod.bind(this);
}
```

```html
[visible]="myBoundMethod"
// or
[visible]="myBoundMethod()"
```

I can't think of a way to make this automatic for people.  Let me know if this works for you.

**Comment by isaacplmann** [comment]
I've updated the readme to mention using this technique.

**Comment by JulienNexonia** [comment]
Works like a charm !
Thanks !
Julien
