### ISSUE TITLE
Possible Position Strategy addition.

### ISSUE THREAD

**Issue by z639** [isaacplmann/angular2-contextmenu#22]
As a general suggestion.

When right-clicking an element to the far right of the screen, when it's parent container has overflow no-scroll the context menu opens almost off screen.

It would be nice to see addition for setting a position for the context menu to open either left or right of the cursor's click position.

Also with the same set-up, scrolling down the page the context menu opens somewhere up the page, I believe this is because the documents scroll height is not taken into consideration when setting the x and y cords.

Thanks.

**Comment by isaacplmann** [comment]
That's a good idea for an enhancement.  I'm not sure when I'll have time to implement it.  Pull request welcome

**Comment by isaacplmann** [comment]
The context menu automatically positions to the left or above the mouse location if the context menu is rendered outside of the body in version 0.7.0.

**Comment by isaacplmann** [comment]
Closing.  Reopen if it isn't fixed.
