### ISSUE TITLE
set enabled based on item

### ISSUE THREAD

**Issue by maariioo** [isaacplmann/angular2-contextmenu#23]
Hi, it could be usefull if I can get item parameter info to set the enabled state.
thanks in advance

**Comment by isaacplmann** [comment]
Yes. Just assign a function to the enabled parameter. The function looks
like this: (item) => Boolean

See
https://github.com/isaacplmann/angular2-contextmenu/blob/master/README.md#binding-this-for-visible-and-enabled-functions

**Comment by maariioo** [comment]
i have just see it. sorry, and many thanks!
