### ISSUE TITLE
Install via systems.config.js?

### ISSUE THREAD

**Issue by jredd** [isaacplmann/angular2-contextmenu#24]
I'm trying to install this component via systemjs and I'm not getting it right at all. Any idea on how to properly install this component via systems?

**Comment by jredd** [comment]
Finally got things to connect and install properly

**Comment by isaacplmann** [comment]
I don't know much about system js. Could you post your solution here to
help others? Glad you figured it out.

**Comment by jredd** [comment]
My issue laid in that my package.json file didn't have the component saved to it which made it no see it at all even though I setup the systems.config.js file properly. so making sure that when you install the app you add --save to the end of the call will save it to the package.json file

**Comment by jredd** [comment]
But here is how my systemjs.config file is setup

```
map : {
      'angular2-contextmenu': 'npm:angular2-contextmenu/'

}
```

```
packages: {
      'angular2-contextmenu': { 'main': 'angular2-contextmenu.js', 'defaultExtension': 'js' }

}
```

That then allowed me to do imports in that looked like

`import { ContextMenuModule } from "angular2-contextmenu";`

**Comment by isaacplmann** [comment]
Thanks!
