### ISSUE TITLE
Template parse errors

### ISSUE THREAD

**Issue by jredd** [isaacplmann/angular2-contextmenu#25]
I keep getting "Can't bind to 'contextMenu' since it isn't a known property of 'li'. Not sure how to get things working properly since I've set things up just like the examples and demo's i've seen posted.

**Comment by isaacplmann** [comment]
It sounds like you didn't import the context menumodule into the module
that you're using.

**Comment by jredd** [comment]
I forgot to mention that the module I'm doing this in is a shared component. When I try and integrate it within a regular component it works fine, just tested in fact. I actually only just tested that when you made the suggestion about not importing the module. So it's failing in inside of a shared component. I have it imported into the the shared components .module file and I even tried importing it into the component that uses the shared components module file as well.

**Comment by isaacplmann** [comment]
I'm assuming your module structure is like this

SharedModule imports (and exports) ContextMenuModule
AppModule imports SharedModule and SomeFeatureModule
SomeFeatureModule tries to use the `contextMenu` directive.

This won't work.  You'll need to have SomeFeatureModule also import SharedModule (or import ContextMenuModule directly)

**Comment by jredd** [comment]
I have the someFeatureModule importing the ContextMenuModule. I thought the problem lied with that I wasn't importing in the right place as well. But I have an import on every module level leading up to the shared component and in the share components module as well and it still tosses the template parse errors... Could the imports in places that it's not need be causing this issue?

**Comment by isaacplmann** [comment]
No, importing in other modules wouldn't affect it.  If you can show me more of your code I could try to help debug.

**Comment by isaacplmann** [comment]
Are you sure the ContextMenuModule is actually being imported?  Maybe do a search for "contextMenu" in your browser's source tab.

**Comment by jredd** [comment]
Yes it's being imported properly and I see it's js files in the sources section in my browser

**Comment by jredd** [comment]
Oh gosh i'm dumb. So you were absolutely right that I have to have the ContextMenuModule imported into the parent containing the shared component. I simply overlooked the fact that I use the shared component across different featureModules. Now that I have it imported into those other componentModules it works just fine. Sorry for the trouble, it was a simple import error. I really wish that you didn't have to do that. That having it import into the shared component was enough for it to function properly.

**Comment by isaacplmann** [comment]
If your SharedModule exports ContextMenuModule, then all you need to do is have all your feature modules import the SharedModule.  Then any libraries that you want to be available globally, you can import/export in the SharedModule without having to add them to each feature module.

You're right.  It is an extra step, but its necessary in order to have AoT compilation.

Glad you figured it out.

**Comment by jredd** [comment]
Yeah it makes sense but it was such an easy thing to overlook. Thank you for the quick responses!
