### ISSUE TITLE
Visibility is ignored if custom styles are used

### ISSUE THREAD

**Issue by perkma** [isaacplmann/angular2-contextmenu#26]
I show and hide the context menu items via booleans like this:
html:
        <template contextMenuItem [visible]="contextMenuShowSearchLink" (execute)="routeTo('/search')">
            go to Search...
        </template>

contextMenuShowSearchLink is a boolean in my component.
Everything worked fine until I've added some custom styles in my main stylesheet:
.angular2-contextmenu .dropdown-menu {
  border: solid 1px darkslategrey;
  background-color: cadetblue;
  padding: 0;
}
.angular2-contextmenu li {
  display: block;
  border-top: solid 1px darkslategrey;
  text-align: center;
}
.angular2-contextmenu li:first-child {
  border-top:none;
}
.angular2-contextmenu a {
  color:darkslategrey;
  display: block;
  padding: 0.5em 1em;
}
.angular2-contextmenu a:hover {
  color:cadetblue;
  background-color:darkslategrey;
}

If I use this custom styles all context menu items are always visible. If I remove the custom styles everything is working fine. Am I doing something wrong? Any help is appreciated. Thanks.

**Comment by isaacplmann** [comment]
The problem was that `.angular2-contextmenu li { display: block; }` overrode the browser's default `[hidden] { display:none }` styling.  I've released version 0.5.3 that now removes invisible context menu items from the DOM instead of using the `[hidden]` attribute.

**Comment by perkma** [comment]
This works perfectly. Thanks for your quick help!
