### ISSUE TITLE
Can the menu be hooked up to the left click?

### ISSUE THREAD

**Issue by atalis** [isaacplmann/angular2-contextmenu#27]
We have a table with an "Actions" column.  Clicking on a button in the column should show a list of options.  That list is really a context menu, except hooking it up to a clickable button makes it apparent to the user that there **is** a menu there.  Since it's a button, right-click doesn't make sense...

**Comment by isaacplmann** [comment]
Yes.  See issue #14.  Since this is the second request, I'll add it to the readme.

**Comment by isaacplmann** [comment]
Here is the [new section in the readme](https://github.com/isaacplmann/angular2-contextmenu#triggering-the-context-menu-with-a-different-event).

**Comment by atalis** [comment]
Great!  Thanks much.

**Comment by isaacplmann** [comment]
Closing.
