### ISSUE TITLE
Unable to Load context menu

### ISSUE THREAD

**Issue by srinathbandi** [isaacplmann/angular2-contextmenu#29]
I have tried with below code and was not able to get context menu. Please suggest what could I do here.
But works if I include the minified js file (angular2-contextmenu.js) from plunker demo instead of npm package.

```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule }   from '@angular/forms';
import { ContextMenuComponent } from 'angular2-contextmenu/src/contextMenu.component';
import { ContextMenuService } from 'angular2-contextmenu/src/contextMenu.service';


import { AppComponent }  from './app.component';

@NgModule({
  imports: [
    BrowserModule,
    FormsModule
  ],
  declarations: [
    AppComponent,
    ContextMenuComponent
  ],
  providers: [ ContextMenuService ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

```
import { Component } from '@angular/core';
import { ContextMenuService } from 'angular2-contextmenu/src/contextMenu.service';

@Component({
  selector: 'my-app',
  template: `
  <h1>Angular2 Context Menu Demo</h1>
  <button class="btn btn-default"
          (contextmenu)="onOtherContextMenu($event, 'blue')">
          Right Click</button>
  <context-menu></context-menu>
  `
})
export class AppComponent {
  public items = [
    { name: 'Small Health Potion', cost: 4 },
    { name: 'Small Mana Potion', cost: 5 },
    { name: 'Iron Short Sword', cost: 12 }
  ];
  
  constructor(private contextMenuService: ContextMenuService) {}

  public onOtherContextMenu($event: MouseEvent, item: any): void {
    this.contextMenuService.show.next({
      actions: [{
        html: () => 'Favorite Color',
        click: (item, $event) => {
          if ($event.altKey) {
            alert('No, yellow!  Aaaauugh!');
          } else {
            alert(item);
          }
        }
      }],
      event: $event,
      item: item,
    });
    $event.preventDefault();
  }
}
```

**Comment by isaacplmann** [comment]
I should update that plunker to use the latest release of the library.  It's pretty old now.  There are 2 things I noticed in your code.

1. In your app module import the ContextMenuModule instead of ContextMenuComponent and ContextMenuService directly.

```typescript
import { ContextMenuModule } from 'angular2-contextmenu';

imports: [
  ContextMenuModule
],
```

2. Rewrite your code to use the [basic example](https://github.com/isaacplmann/angular2-contextmenu#template) or [directly calling ContextMenuService](https://github.com/isaacplmann/angular2-contextmenu#context-menu-in-a-different-component).

**Comment by srinathbandi** [comment]
Thanks you, Now I could see the menu.

One quick help, observed menu doesn't disappear when we scroll the page where browser context menu generally disappear when we scroll in Chrome. Is there any config or logic available to do so? (IE doesn't scroll at all when right click context menu was opened)

Regards,
Srinath

**Comment by isaacplmann** [comment]
I haven't put any logic around managing scrolling.  Feel free to open another issue about it and I can work on it as an enhancement.  Better yet, submit a PR!

**Comment by srinathbandi** [comment]
I overrided the styles of the menu to mange it. I got what I need.

Thank you.
