### ISSUE TITLE
How do i make a context menu with a separator?

### ISSUE THREAD

**Issue by PolarbearDK** [isaacplmann/angular2-contextmenu#30]
I use bootstrap3 and would like to add a separator to a context menu.

Normally done by:
`<li role="separator" class="divider"></li>`

Is it possible?

**Comment by isaacplmann** [comment]
No, not with the current code.  Let me see what I can do.

**Comment by PolarbearDK** [comment]
An empty template could indicate a separator:

`<context-menu>
  <template contextMenuItem (execute)="onMenuActivated(...)">Foo</template>
  <template contextMenuItem></template>
  <template contextMenuItem (execute)="onMenuActivated(...)">Bar</template>
</context-menu>`

**Comment by isaacplmann** [comment]
I just implemented this version 0.6.0.  Make a template like this:

```html
<template contextMenuItem divider="true"></template>
```

That's easier than trying to check if there is anything inside the template.

**Comment by PolarbearDK** [comment]
Thanks.
