### ISSUE TITLE
What does the separator look like?

### ISSUE THREAD

**Issue by atalis** [isaacplmann/angular2-contextmenu#31]
Hi,

I'm inserting a divider into the menu, but it looks odd: 1) there is no actual separator line, just a few-inch-thick gap between items; and 2) it changes color on hover, just like the other menu items.  I can't tell whether this is the intended look, or whether this is a result of our extensive set of CSS (although I can't find any particular style that would cause this).

What is the divider supposed to look like?

**Comment by isaacplmann** [comment]
This is what it looks like in the demo app when I run from source:

![image](https://cloud.githubusercontent.com/assets/861504/21111576/293354c2-c070-11e6-8aef-8e60534c2ba6.png)

Hovering over the divider doesn't highlight it, and the cursor reverts to the default cursor instead of the pointer.  I'm just using default bootstrap 3 css in the demo.

**Comment by atalis** [comment]
Thanks!  I'll dig into our CSS then.  I wasn't sure, because we inherited a large set of CSS from a template library, and I didn't see anything specific to separators there.

**Comment by atalis** [comment]
Hmm, I checked in our running code, and the divider row shows up as an empty anchor:
![image](https://cloud.githubusercontent.com/assets/14112109/21154918/2385419c-c13e-11e6-8a46-6b16a8621a13.png)

Our template looks like this:
`<context-menu #ctxtMenu id="actionsMenu">
	<template contextMenuItem (execute)="onItemClick('View')"> View </template>
	<template contextMenuItem (execute)="onItemClick('Edit')"> Edit </template>
	<template contextMenuItem (execute)="onItemClick('Delete')"> Delete </template>
	<template contextMenuItem divider="true"></template>
  <template contextMenuItem (execute)="onItemClick('Delete')"> Other </template>
</context-menu>`

Perhaps we're doing something wrong?  Your Plunker demo (http://plnkr.co/edit/wpJXpEh4zNZ4uCxTURx2?p=preview) isn't using the <context-menu> style.  Could you please update it with the new syntax, so that I could compare our code/style to your example?

Thank you,
Anna

**Comment by atalis** [comment]
Apparently, this was fixed in 0.6.0, and I had 0.5.3 installed.  It looks good now.

**Comment by isaacplmann** [comment]
Yes, that would account for it.  Sorry I didn't think of that.  Glad you found the solution.
