### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by PoojaVM** [isaacplmann/angular2-contextmenu#33]
Hi,
Can we please have the option of closing the right click context menu drop down on when escape key is pressed or user scrolls thorugh the window?

**Comment by isaacplmann** [comment]
Sounds like a good feature.  I'm on vacation this week, but I'll try to 
get to it next week.

**Comment by PoojaVM** [comment]
Thank you for considering :)

**Comment by isaacplmann** [comment]
This should be implemented in 0.7.0

**Comment by isaacplmann** [comment]
Closing.  Reopen if it isn't fixed.

**Comment by PoojaVM** [comment]
This update is working fine. Thank you.

**Comment by PoojaVM** [comment]
Hi @isaacplmann,
The closing of context menu on pressing escape key isn't working for safari browser.
Can you please let me know whether this is an issue with the browser or not being handled in the update?

**Comment by isaacplmann** [comment]
This was a bug.  It should be fixed in 0.7.1.  Please reopen if it isn't.
