### ISSUE TITLE
Add an offset

### ISSUE THREAD

**Issue by JulienNexonia** [isaacplmann/angular2-contextmenu#37]
Hi,
Thanks for the lib.
I am currently using the angular2-contextmenu in association with the angular2-tree-component.
On my page I have a fixed header at the top (height : 50px) and the main content of the page is in an absolute position.
When I right click on a node of tre tree the context menu shows, but its position is moved 50px to the bottom.
I would like to have the possibility to add an offset (or maybe two : one for top and one for left directions) (possibly by overriding a param in options) to update the position of the context-menu according to the design of the page.
What do you think ?
Thanks !
Julien

**Comment by isaacplmann** [comment]
Can you give me a plunker or git repo that reproduces this?  (Or you could paste your html/css code directly into the issue.)  I want to make sure I fully understand your situation.

Also, you can add your own offset in css directly like this:

```css
.angular2-context-menu > .dropdown-menu {
  margin-top: 50px;
  margin-left: 5px;
}
```

**Comment by JulienNexonia** [comment]
Hi,
I manage to make it work by adding 
```
.angular2-context-menu > .dropdown-menu {
  margin-top: -50px;
}
```
This way, the context-menu is shifted to the top.
As the value is exactly equals to the height of my header, the user experience is very smooth now !
Thanks for pointing out the solution ;-)
Julien

**Comment by JulienNexonia** [comment]
By the way, the date of version 0.7.0 in the changelog refers the same date than the version 0.6.0.
Woul be nice if you can change it.
Thanks.
Julien

**Comment by isaacplmann** [comment]
Yes, good catch.  Fixed.
