### ISSUE TITLE
scrolling issue with the context menu

### ISSUE THREAD

**Issue by shahbazshueb** [isaacplmann/angular2-contextmenu#40]
When the context-menu is open in a scrollable content then the menu also scrolls down instead of staying fixed at its position. The menu should close when the content is scrolled down or it should stay fixed at the position.
![context menu scroll problem](https://cloud.githubusercontent.com/assets/10958507/21801963/ab13876e-d745-11e6-929b-7066891bf4a5.PNG)

**Comment by isaacplmann** [comment]
You're right.  Do you know how to get the parent element that is the scroll container for a particular element?  I have a scroll listener for the body, but not for an arbitrary scroll container.

**Comment by isaacplmann** [comment]
This issue was moved to isaacplmann/ngx-contextmenu#6
