### ISSUE TITLE
How we can use context menu on Kendo-dialog 

### ISSUE THREAD

**Issue by aditiparanjape** [isaacplmann/angular2-contextmenu#43]
Hi,

I have added my base context menu on app.component.ts as follows
 template: `<div id="outer-outlet">               
                <router-outlet></router-outlet>
                <context-menu></context-menu>
                </div>`,

this works perfect for base page but when I open kendo-dialog the context menu is not coming unless I need to add that on kendo dialog again.

If I add context menu on kendo dialog sometimes while opening context menu it's giving me error
app_libs_bundle.js:185031 TypeError: Cannot read property 'tagName' of null
    at ContextMenuComponent.onMenuEvent (app_libs_bundle.js:150868)
    at SafeSubscriber._next (app_libs_bundle.js:150755)
    at SafeSubscriber.__tryOrUnsub (app_libs_bundle.js:183079)
    at SafeSubscriber.next (app_libs_bundle.js:183034)
    at Subscriber._next (app_libs_bundle.js:182988)
    at Subscriber.next (app_libs_bundle.js:182952)
    at Subject.next (app_libs_bundle.js:182485)
    at GridComponent.onOtherContextMenu (app_libs_bundle.js:149939)
    at View_GridComponent2.handleEvent_1 (component.ngfactory.js:358)
    at HTMLButtonElement.<anonymous> (app_libs_bundle.js:163020)
ErrorHandler.handleError @ app_libs_bundle.js:185031.

I have also upgraded contextmenu npm to 0.7.3

Could you please help me out in this?

**Comment by isaacplmann** [comment]
The specific error you mentioned should be fixed 0.7.4, but you should be able to have the context menu in `app.component`.  Can you give me more information about your set up so that I can try to reproduce it?  A plunker or a git repo would be even better.

**Comment by aditiparanjape** [comment]
I have basic context menu that I have added in app.components.ts. then I am using this on my main page kendo-grid. I am facing issues when I need to show context menu on Kendo dialog because on kendo dialog also I am showing Kendo grid. and I need to add context menu on pop up also since if I only add it on app.componenets.ts it's not showing on pop up.

**Comment by isaacplmann** [comment]
Is the kendo dialog in a lazy loaded module?  You might be in a scenario where there are multiple ContextMenuService instances.

**Comment by isaacplmann** [comment]
Closing.  Please open an issue at [ngx-contextmenu](https://github.com/isaacplmann/ngx-contextmenu) if this is still a problem.
