### ISSUE TITLE
please provide example on how to use with ng-cli

### ISSUE THREAD

**Issue by born2net** [isaacplmann/angular2-contextmenu#44]
please provide example on how to use with ng-cli

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by born2net** [comment]
also typo in readme:

```
<li *ngFor="let item of items" (contextmenu)="onContextMenu($event, item)">Right Click: {{item.name}}</li>
```

**Comment by isaacplmann** [comment]
Typo is fixed.  Thanks.

I'm not sure what you mean by an example using the angular-cli.  Using this library has no bearing on whether you use the cli or not.  The same set up instructions apply.  Is there something confusing about the instructions?

**Comment by isaacplmann** [comment]
By the way, I was just watching your "Advanced Angular tips and tricks" video yesterday - good stuff.  Thanks for sharing those tips.

**Comment by born2net** [comment]
my pleasure... ignore cli bug.
be posting new adv tips video soon
Sean.

**Comment by born2net** [comment]
and good job on this lib, it's really cool, will use it in our app at
http://www.digitalsignage.com
