### ISSUE TITLE
plunker 0.2.0 version

### ISSUE THREAD

**Issue by Meniou** [isaacplmann/angular2-contextmenu#46]
Is there a Plunker example of the new syntax (version 0.2.0).
I cannot get it to work.

When I use it in an li tag I get the following exception :
Can't bind to 'contextMenu' since it isn't a known property of 'li'.

**Comment by isaacplmann** [comment]
I haven't gotten a plunker working with the new syntax - SystemJS still confuses me.

However, that error is most likely because you haven't imported the `ContextMenuModule` into your app.

Like this:
```ts
@NgModule({
  ...
  imports: [
    ContextMenuModule,
    ...
  ]
})
export class AppModule {};
```

**Comment by Meniou** [comment]
Yes, that was it. Thank you very much !
