### ISSUE TITLE
How to call 'contextmenu' from the separate ngModule

### ISSUE THREAD

**Issue by kuncevic** [isaacplmann/angular2-contextmenu#47]
Some time ago I was reading this article https://medium.com/@tarik.nzl/making-use-of-dialogs-in-material-2-mddialog-7533d27df41#.lx6pk2u19 that demonstrating how to reuse `material2` dialogs. So I if I can come up wit similar solution in case of `angular2-contextmenu`.

What I am trying to achieve is to create a module that contain my generic menu component and a service. I can call that service form any component by passing the  `menuOptions` . 

That is my context menu ngModule:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ContextMenuModule, ContextMenuService } from 'angular2-contextmenu';

import { AppContextMenuService } from './app-context-menu.service';
import { AppContextMenuComponent } from './context-menu/app-context-menu.component';

@NgModule({
  imports: [
    CommonModule,
    ContextMenuModule,
  ],
  exports: [
    AppContextMenuComponent
  ],
  declarations: [
    AppContextMenuComponent
  ],
  providers: [
    AppContextMenuService,
    {provide: AppContextMenuComponent, useValue: new AppContextMenuComponent(new ContextMenuService()) }
  ],
  entryComponents: [
    AppContextMenuComponent,
  ]
})
export class AppContextMenuModule { }
```
That is my service:
```
import { Observable } from 'rxjs/Observable';
import { Injectable, ViewContainerRef, Inject } from '@angular/core';
import { ContextMenuService } from 'angular2-contextmenu';
import { AppContextMenuComponent } from './context-menu/app-context-menu.component';

@Injectable()
export class AppContextMenuService {

  constructor(
    private contextMenuService: ContextMenuService,
    private contextMenuComponent: AppContextMenuComponent) { }

  public showContextMenu($event: MouseEvent, item: any): void {
    this.contextMenuComponent.onContextMenu($event, item);
  }
}
```

 that is my component:
```
import { Component, OnInit, ViewChild } from '@angular/core';
import { ContextMenuService, ContextMenuComponent as ctxMenuComponent } from 'angular2-contextmenu';

@Component({
  selector: 'app-context-menu',
  templateUrl: './app-context-menu.component.html',
  styleUrls: ['./app-context-menu.component.scss']
})
export class AppContextMenuComponent implements OnInit {

  public menuOptions = []; //TODO: need to pass options here from the caller component

  constructor(private contextMenuService: ContextMenuService) {
  }

  ngOnInit() {
  }

  public onContextMenu($event: MouseEvent, item: any): void {
    this.contextMenuService.show.next({
      actions: this.menuOptions,
      event: $event,
      item: item,
    });
    $event.preventDefault();
    console.log('onContextMenu');
  }
}
```

So right now I am missing two things:
1) Dialog is not showing when I am calling that through my service. (this one is more important)
2) Didn't yet figure out how to pass `menuOptions` to my `app-context-menu-component.ts`  

I just pull my repo here https://github.com/kuncevic/context-menu-app if you can check it out by any chance to see the  full picture what I am trying to achieve.  It really would of be amazing if you can give some suggestions on that.

**Comment by isaacplmann** [comment]
First, don't use the deprecated imperative way of creating the context menu.  See #15 for an example of how to use the `menuOptions` object in your template and not get the deprecation warnings in your console.

Second, it looks like the easiest way to pass in the `menuOptions` is to add them as a parameter on `AppContextMenuComponent.onContextMenu` and `AppContextMenuService.showContextMenu`.

Hope that helps.

**Comment by kuncevic** [comment]
@isaacplmann if I use declarative way how would is stick to this PR https://github.com/swimlane/ngx-datatable/pull/331/commits/eddf1c57696c45f4633e54b4bac98fb01c607a7f with `(rowContextmenu)="onContextMenu($event)">`?

**Comment by isaacplmann** [comment]
That's funny.  I'm actually using ngx-datatable in my own app (and I submitted the PR to add the rowContextMenu event).  Here's how I'm adding context menus to the data table:

```html
<ngx-datatable (rowContextMenu)="onContextMenu($event.event, $event.row)" ...></ngx-datatable>
<context-menu>
  <template let-item contextMenuItem *ngFor="let action of contextUserActions" (execute)="action.execute(item)">
    {{action.label}}
  </template>
</context-menu>
```

```ts
public onContextMenu(event: MouseEvent, item: any): void {
  this.contextMenuService.show.next({ event, item });
  event.preventDefault();
  event.stopPropagation();
}
```

No need for `[contextMenu]="contextMenu" [contextMenuSubject]="rows"` on the `ngx-datatable`.

**Comment by kuncevic** [comment]
@isaacplmann thanks for your help, I will review my code and comeback.

**Comment by kuncevic** [comment]
Just achieved what I wanted. Also I pushed the sample code here: https://github.com/kuncevic/context-menu-app. In a sample app am just passing the context menu actions using rxjs Subject. 

@isaacplmann thank you for you input.
