### ISSUE TITLE
 'ContextMenuComponent' is not exported by node_modules\angular2-contextmenu\angular2-contextmenu.js

### ISSUE THREAD

**Issue by AnthonyBr** [isaacplmann/angular2-contextmenu#48]
Hello,

When I generate my angular2 project:
`node_modules\.bin\rollup -c rollup-config.js`

I have the error in the title:

```
?   'ContextMenuComponent' is not exported by node_modules\angular2-contextmenu\
angular2-contextmenu.js
```

To bundle my project, I use rollup, as described here:
`https://angular.io/docs/ts/latest/cookbook/aot-compiler.html`

As said in the documentation:
Rollup can only Tree Shake ES2015 modules which have import and export statements.

And ContextMenuComponent has no export statement.

The project works well when I start the project with systemjs.

Thank you for help,
A. Breneliere

**Comment by isaacplmann** [comment]
You're right.  I'm not really sure the best way to export both commonjs (for webpack et al.) and es2015 (for rollup).  If you could point me towards another library that does this well or a how-to article, that will help me resolve this.

**Comment by isaacplmann** [comment]
This issue was moved to isaacplmann/ngx-contextmenu#5
