### ISSUE TITLE
Support bootstrap 4 by enabling the ability to add classes to the anchor tags

### ISSUE THREAD

**Issue by TrevorBroderick1** [isaacplmann/angular2-contextmenu#5]
Bootstrap 4 requires the 'dropdown-item' class on a tags to style it properly.

**Comment by isaacplmann** [comment]
I think I'll add an optional useBootstrap4 input on the contextMenu component that will change the template accordingly.

**Comment by TrevorBroderick1** [comment]
That works, thank you!

**Comment by isaacplmann** [comment]
Should the dropdown-item class be on the <li> element or the <a> element?  I know that bootstrap 4 doesn’t use list tags, but it would be easier if I could just modify classes instead of html structure.

**Comment by TrevorBroderick1** [comment]
I believe it should be on the <a> element. I just tried it on the <li> element and it doesn't give the expected style.

**Comment by isaacplmann** [comment]
Implemented in version 0.1.9 on npm.

```html
<context-menu [useBootstrap4]="true"></context-menu>
```

**Comment by TrevorBroderick1** [comment]
Cheers
