### ISSUE TITLE
Multiple context menus opened by ContextMenuService

### ISSUE THREAD

**Issue by LeGaby** [isaacplmann/angular2-contextmenu#50]
Hi guys! I have 2 context menus in the same component (each one referenced by a template reference variable like you specified), both have to use the (click) event in order to be opened with the left click of the mouse. According to your documentation, I should use the ContextMenuService to do that. Currently, the 2 context menus open at the same time, which makes sense to me. I would like to specify to the ContextMenuService which menu he has to open, depending on the function called on the (click) event. Is this even possible ? Am I doing it the wrong way ?

**Comment by isaacplmann** [comment]
Check out this [issue comment](https://github.com/isaacplmann/angular2-contextmenu/issues/32#issuecomment-275779875).  I need to put this in the documentation.

**Comment by LeGaby** [comment]
Yeah, I found it 10 minutes after posted my issue but no way to delete my issue. You're right, have it written in the documentation might be really useful for others.

**Comment by isaacplmann** [comment]
Checkout the new [documentation](https://github.com/isaacplmann/angular2-contextmenu#context-menu-in-a-different-component).  Does that explain it enough?

FYI, there's a `Close` button at the bottom of the issue, if you decide you've solved it.

**Comment by LeGaby** [comment]
Well, I think it explains enough. Thanks for the reply and the documentation update.
