### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by jried31** [isaacplmann/angular2-contextmenu#53]
Getting this error...Would you be able to provide assistance?

In my system.config file I added the following:
map{
      'angular2-contextmenu':       'node_modules/angular2-contextmenu/angular2-contextmenu.js'
},
packages{
      'angular2-contextmenu':{
        "defaultExtension":'js'
      },
}
Then included the ContextMenuModule inside of app.module.ts.

This error occurs when I implement you examples defined [here](http://plnkr.co/edit/wpJXpEh4zNZ4uCxTURx2?p=preview) and [here](https://github.com/isaacplmann/angular2-contextmenu/blob/master/README.md)

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/angular2-contextmenu/src/contextMenu.options
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/angular2-contextmenu/src/contextMenu.options
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/node_modules/angular2-contextmenu/src/contextMenu.options as "./src/contextMenu.options" from http://localhost:3000/node_modules/angular2-contextmenu/angular2-contextmenu.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/node_modules/angular2-contextmenu/src/contextMenu.options as "./src/contextMenu.options" from http://localhost:3000/node_modules/angular2-contextmenu/angular2-contextmenu.js

**Comment by isaacplmann** [comment]
I don’t understand SystemJS very well at all.  Updating that demo has been on my todo list for a long time, but I haven’t done it because I get lost every time I look at the system js config file.  If you want to give me a primer on how system js works, I’d be happy to help you with any issues with the angular2-contextmenu library itself.

**Comment by jried31** [comment]
SystemJS is essentially a package manager. It looks for a main file (index or in this case angular2-contextmenu.js) and performs the necessary linkages in the JS file. Now, I'm not experienced yet w/ Angular to know how Angular handles these compilations. However basically it seems as though it exports the compiled packages to a System.config variable.

Hmm, would it be possible to try another alternative? If I were to import your source code to my project would be possible to simply drop the folders in or are there other dependancies needed?

**Comment by isaacplmann** [comment]
There aren't any package dependencies, other than Angular itself.  I know you can use SystemJS with Angular, but I don't know how it sets everything up.

It may be that I need to bundle the library in a special way to allow people to import it with SystemJS (as opposed to webpack).  There are lots of different options for module output (CommonJS, UMD, others?).  I stopped tinkering with my build process once I got it to work for webpack.

Build process is not fun.

**Comment by jried31** [comment]
No it's not :( ... I was able to just now successfully import just your files in the src folder...The webpage atleast loads now. However, when I click the button I get an error. Let me investigate and I'll post to you.

**Comment by jried31** [comment]
Ok, so when I click the link nothing pops up. I'm using the example code from the demo here:
http://plnkr.co/edit/wpJXpEh4zNZ4uCxTURx2?p=preview

When I click the link the view doesn't popup, however the callback function fires but this code doesn't show the popup. 
this.contextMenuService.show.next({
      actions: this.menuOptions,
      event: $event,
      item:item
    });

**Comment by isaacplmann** [comment]
So your `onContextMenu` function is called, but the angular2-contextmenu doesn't actually show.  This demo actually uses an old method of triggering the context menu, so that only makes things messier.  Here is the [new syntax](https://github.com/isaacplmann/angular2-contextmenu#template).

- Have you included `<contextmenu></contextmenu>` somewhere in the component template?
- What is `this.menuOptions`?  Have you tried putting `<template>` tags inside of `<contextmenu>` instead of using the `actions` property of the `contextMenuService`?
- Can you look at the DOM to see if the context menu is added, but isn't being shown because of css problems?

**Comment by jried31** [comment]
I forgot to include: <contextmenu></contextmenu>. However, the menu displays at the top of the page and not where I clicked. How would I go about making the contextmenu appear where the user left clicked? Would this require modifying CSS or is there an attribute property?

**Comment by isaacplmann** [comment]
What is the `$event` that is being passed in?  Is it a MouseEvent?

**Comment by jried31** [comment]
yes

**Comment by isaacplmann** [comment]
The context menu should automatically be placed at the point { $event.clientX, $event.clientY }

Can you verify that the event has correct clientX and clientY values?

**Comment by isaacplmann** [comment]
And can you send me your SystemJS config so that I can get an updated plunker working?

**Comment by jried31** [comment]
As for the Dropdown location: I think the X,Y values are relative to the Container that the box is being clicked in rather than global values. For instance the click location is X: 224 Y: 345 and the window shows up at top:345 and left:224, but the actual click location is not there, so it's not adding the global position. Is what it seems.
------
SystemJS.config has the following attributes, and this was what I included to the "map" and "packages" field. However, the error I originally pasted was the result of this. I do know that this is prettymuch the propper config, but there's some files that aren't included in the main file "angular2-contextmenu.js."
map{
'angular2-contextmenu': 'node_modules/angular2-contextmenu/angular2-contextmenu.js'
},
packages{
'angular2-contextmenu':{
"defaultExtension":'js'
},
}

**Comment by isaacplmann** [comment]
I've been working on bugs like this for the last month or two.

I'll need to know the css properties on all the ancestors of the <contextmenu> element.  Specifically, any `position` or `transform` properties.

And what version of angular2-contextmenu are you using?

**Comment by jried31** [comment]
Hmm, is there a way for me to mod the context menu css to float center screen?

**Comment by isaacplmann** [comment]
[Yep](https://github.com/isaacplmann/angular2-contextmenu#custom-styles).  Like this:

```css
.angular2-contextmenu .dropdown-menu {
  top: 50vh !important;
  left: 50vw !important;
  margin-top: -100px !important; // half the height of the menu
  margin-left: -50px !important; // half the width of the menu
}
```

**Comment by jried31** [comment]
Thanks...I decided to do something else:
1. In your file contextMenu.component, removing "adjustX" and "adjustY" for mouseLocation makes the panel show up exactly where I click...I'm now trying to add a left/right side offset so that I can have the panel open on right side vs the left side of the button click. 

In other words, when I click the button and lets say the buttons' on the right side of the page, the panel expands and it's off the screen. So if I add a feature that offset's it "left" location then that solves the problem.
