### ISSUE TITLE
top and left positioning of the context menu

### ISSUE THREAD

**Issue by asafpaz-ness** [isaacplmann/angular2-contextmenu#54]
Hi,
I've been using your angular2-contextmenu for some time now and it was working great!
Yesterday I've updated to the latest version of Angular (2.4.9).
And now there is something quirky with the "top" and "left" position which you set when i "right click" an item. Its not being calculated right and because of that the context menu is positioned not in the right location.
Any clue what can it be?

**Comment by isaacplmann** [comment]
I’m using angular 2.4.9 with angular2-contextmenu without issue, but I have been working on positioning issues over the last few months.  Problems arise when some parent element of the `<context-menu>` element have certain css properties: `transform`, `position: absolute`, or `position: fixed`.  Is that the case for you?

**Comment by asafpaz-ness** [comment]
I did set "position:absolute" to the <div> on which i right clicked. But the <context-menu> component is not inside that div. Its parent is actually the component element and its parent is a normal position:relative element.
It was working perfectly before... :(
I'll keep you posted if I find out why it is happening.

One last thing i did, which i forgot to tell you. I'm almost sure its not related, but I'm using right-to-left html.
So i overwritten some of your CSS using this:

.angular2-contextmenu .dropdown-menu {
right:auto!important;
left:0;
}

Thanks.

**Comment by isaacplmann** [comment]
The css you added may be related.  Try removing it and see if the problem goes away.  That will help me find a solution.

Can you also send a screenshot?

**Comment by asafpaz-ness** [comment]
Sorry. The problem remains. It's something else. Maybe some other 3rd party Module is affecting it.
Attached screen shots.
![2](https://cloud.githubusercontent.com/assets/22073082/23999656/b331277c-0a61-11e7-9977-2620defb8f49.png)
![1](https://cloud.githubusercontent.com/assets/22073082/23999657/b3340488-0a61-11e7-9996-9190f609ca9a.png)

**Comment by isaacplmann** [comment]
Did you update any other libraries when you updated angular?

Are you able to put the `<context-menu>` tag on the `body` element directly?  Just to confirm that that isn't the problem.

**Comment by asafpaz-ness** [comment]
I moved from ng2-bootstrap 1.3.3 to 1.4.0 .. i tried to do a roll back, but I still got this issue.
I've upgraded to angular-cli 1.0.0-rc2.
And i updated your angular2-contextmenu from 0.7.1 to 0.8.1... Also tried to do a rollback.
I just checked and if I place the '<context-menu>' in the root body, its working correctly.

**Comment by asafpaz-ness** [comment]
I just found the culprit.
I managed to roll back to angular2-contextmenu version 0.7.1 and now everything is working fine again.
I had on my package.json ~0.7.1, so i never really rolled back and it automatically updated to 0.8.1.
It looks like a bug with one of your latest changes.
Let me know if you need some more information in order to resolve that issue.

**Comment by isaacplmann** [comment]
I keep hitting positioning errors and it’s different for everyone.  I think the real solution is to automatically add the context menu on the body element - I’ll let you know when I get that working.

**Comment by isaacplmann** [comment]
Should be fixed by the move to [ngx-contextmenu](https://github.com/isaacplmann/ngx-contextmenu).  Please open an issue there if this doesn't work.

**Comment by asafpaz-ness** [comment]
Its working perfect now. Well done! 👍
