### ISSUE TITLE
Divider and Position Issue

### ISSUE THREAD

**Issue by smhnkmr** [isaacplmann/angular2-contextmenu#55]
Thanks for the component @isaacplmann 

I am facing two issues here,
1. Even when I set the 'divider' to true (tried in both template and menu options approach), the divider is not getting visible.
2. The position is not proper, it always goes with some offset to top left position. 

Note that, I am using the styles defined for .angular2-context-menu in the documentation. 

Can you please help me resolve this? Thanks in advance.

**Comment by isaacplmann** [comment]
Can you paste in the relevant code?  Show me your css, template file and typescript that relate to the context menu.

Thanks.

**Comment by smhnkmr** [comment]
Thanks for your response @isaacplmann .

The issues are fixed. The issue is with the relative positioning override and divider works fine when defining it in the template.

I have referred your demo project and resolved these issues. Thanks.
