### ISSUE TITLE
Google maps context menu

### ISSUE THREAD

**Issue by ikeashark** [isaacplmann/angular2-contextmenu#56]
I have implemented the context menu to my google map, but for some reason it only works before the map has been loaded in.

here are my codes
HTML:
[map.component.html (1).txt](https://github.com/isaacplmann/angular2-contextmenu/files/854411/map.component.html.1.txt)

Typescript:
[map component typescript.txt](https://github.com/isaacplmann/angular2-contextmenu/files/854415/map.component.typescript.txt)

newb at both angular 2 and github here, sorry in advance

**Comment by isaacplmann** [comment]
newbs are great!  It means more people joining the community.

Can you put a `console.log` in your `onContextMenu` function?  That we can know if that's even being called.

**Comment by ikeashark** [comment]
i placed a `console.log` in the function. the function is not being called when my map is loaded.

**Comment by isaacplmann** [comment]
1. It looks like `sebm-google-maps` doesn't emit the default `(contextmenu)` event.  Instead it has an output of [mapRightClick](https://angular-maps.com/docs/api/latest/ts/core/SebmGoogleMap-directive.html#Outputs).

2. I don't think you need the `*ngFor="item of items"` (unless you're planning to have multiple maps on the page).

Try this in the html:
```html
<sebm-google-map [latitude]="lat" [longitude]="lng" [zoom]="zoom" [disableDefaultUI]=false [zoomControl]="false" (mapClick)="mapClicked($event)"
         (mapRightClick)="onContextMenu($event)" >
```

The `item` value in `onContextMenu` will be undefined, but that's fine.  Let me know if your `console.log` starts sending messages to the console.

**Comment by ikeashark** [comment]
i have since edited my codes alot since i first posted this issue so here are the new codes, though i dont think i have edited anything related to the context menu
HTML:
[map component.html.txt](https://github.com/isaacplmann/angular2-contextmenu/files/874378/map.component.html.txt)

Typescript:
[map component.ts.txt](https://github.com/isaacplmann/angular2-contextmenu/files/874379/map.component.ts.txt)


The component is being called and send the messsage but there are errors

![console](https://cloud.githubusercontent.com/assets/26476842/24387441/ba7d5b14-13a7-11e7-96c7-d04b7f203b03.png)


Error in my console.log once edit my codes to output of mapRightClick:

Uncaught ViewWrappedError

EXCEPTION: Cannot read property 'document' of undefined

TypeError: Cannot read property 'document' of undefined

Uncaught TypeError: Cannot read property 'document' of undefined

P.S Thank you very much for spending time to help me with this.

**Comment by isaacplmann** [comment]
Can you change your console.log to this:
```ts
console.log('ayy context menu', $event);
```

And send me the event object that is printed out.  It looks like it doesn't have some properties that I expect it to have.  And what browser are you using?

**Comment by ikeashark** [comment]
The new message in my console:
ayy context menu Object {coords: Object}

![console with event](https://cloud.githubusercontent.com/assets/26476842/24435675/5b2491ce-1469-11e7-9916-291ba29950f7.png)


For my application im using google chrome

**Comment by ikeashark** [comment]
found this error in my IDE:

file: 'file:///c%3A/Users/L33902/Desktop/Projects/mapit/node_modules/angular2-contextmenu/tsconfig.json'
severity: 'Error'
message: 'File 'c:/Users/L33902/Desktop/Projects/mapit/node_modules/angular2-contextmenu/./typings/browser.d.ts' not found.'
at: '1,1'
source: 'ts'

could this be the problem?

**Comment by isaacplmann** [comment]
The problem is that `sebm-google-maps` is not giving you an actual `MouseEvent` just the `coords` part of it.

I'd file an issue with them asking for the whole event to be emitted by the EventEmitter.  They could emit an additional `event` or `sourceEvent` property if they want to make sure not to make breaking changes.

You could theoretically create your own event but I have no idea how to calculate a browser x/y coordinate from their provided lattitude and longitude.  Here is how you could create your own event (with static x and y values) if you just want to see the context menu show up.

```ts
let ev = new MouseEvent('contextmenu', {
        'view': window,
        'clientX': 10,
        'clientY': 20
    });
this.contextMenuService.show.next({
      // Optional - if unspecified, all context menu components will open 
      contextMenu: this.contextMenu,
      event: ev,
      item: item,
    });
```

**Comment by ikeashark** [comment]
The reason i wanted to do this was to allow for user to open a context menu at a point to drop a marker but from my understanding i cant do this anymore?

Well it cant be help angular 2 is still at a very early stage.

Thanks for the help. I guess this can be closed for now?

**Comment by isaacplmann** [comment]
You can do it if you get the other library to pass the MouseEvent to you 
- otherwise no.
