### ISSUE TITLE
Getting error when adding <context-menu> [help needed]

### ISSUE THREAD

**Issue by meiuqer** [isaacplmann/angular2-contextmenu#57]
> Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]'.

This is what my console gives when i just add a < context - menu >. I already added the property bindings [contextMenu] and [contextMenuSubject] and followed the example but when i add the < context - menu > the console gives the above error. Am i doing something wrong? I'm just copy pasting the example you gave. The console also doesn't give me any location on where the error happens so it's hard to debug.

**Comment by isaacplmann** [comment]
That is a difficult error to debug.  Can you paste some of your code or create a simple git hub repo to reproduce the problem?

**Comment by meiuqer** [comment]
I already made my own custom context menu. But i tried it again and cant recreate the error :) sorry about that.

**Comment by isaacplmann** [comment]
No problem.  Glad you found something that works for you.
