### ISSUE TITLE
separator/divider

### ISSUE THREAD

**Issue by gjenner** [isaacplmann/angular2-contextmenu#58]
is it possible to add a divider (or separator) in code rather than HTML?

**Comment by isaacplmann** [comment]
[Kind of](https://github.com/isaacplmann/angular2-contextmenu/issues/15#issuecomment-252943752), I updated the linked comment to show how to use a dynamic data in code to update the html template.  I think that html should stay in templates.

**Comment by gjenner** [comment]
Thank you, I have been able to populate in code-behind, but the example of divider does not seem to work.  It allocates the space, but does not show the divider, and is selectable.

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
I guess I’ll have to actually test my code sample before sharing it.  I’ll having a working example for you soon.

**Comment by gjenner** [comment]
Thank you so much

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
I just updated the demo code in the repo to create a divider like in the linked comment.  It's working in the demo.  What version of bootstrap are you using?  Can you show me what the rendered html looks like when the divider doesn't show correctly?  Did you add `[divider]="action.divider"` to the `contextMenuItem`?

**Comment by gjenner** [comment]
OK, a couple of challenges

1.       My HTML is just <context-menu></context-menu>, as I push everything in code-behind (I am old school that way)

2.       When I do add an empty <template [divider]=”action.divider”></template>, I get ‘divider’ is not a known property of ‘template’

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
You need to add the `contextMenuItem` directive to the template element.

```html
<template contextMenuItem [divider]=”action.divider”></template>
```

**Comment by gjenner** [comment]
Thank you for your patience.  Cannot read property ‘divider’ pf undefined

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
That means that `action` is undefined.  You could statically set `[divider]="true"` or use all the example code:

``` html
<ul>
    <li *ngFor="item in items" [contextMenu]="contextMenu" [contextMenuSubject]="item">Right Click: {{item.name}}</li>
</ul>
<context-menu>
  <template *ngFor="let action of contextMenuActions" contextMenuItem let-item
    [visible]="action.visible" [enabled]="action.enabled" [divider]="action.divider"
    (execute)="action.execute($event.item)">
    {{ action.html(item) }}
  </template>
</context-menu>
```

``` js
@Component({
  ...
})
export class MyContextMenuClass {
  public items = [
      { name: 'John', otherProperty: 'Foo' },
      { name: 'Joe', otherProperty: 'Bar' }
  };
  @ViewChild(ContextMenuComponent) public contextMenu: ContextMenuComponent;
  public contextMenuActions = [
        {
          html: (item) => `Say hi!`,
          click: (item) => alert('Hi, ' + item.name)
          enabled: (item) => true,
          visible: (item) => item.type === 'type1',
        },
        {
          divider: true,
          visible: true,
        },
        {
          html: (item) => `Something else`,
          click: (item) => alert('Or not...'),
          enabled: (item) => false,
          visible: (item) => item.type === 'type1',
        },
      ];
}
```

**Comment by isaacplmann** [comment]
Can you post your entire html snippet?

**Comment by gjenner** [comment]
Made item [visible]=>true, fixed that, but still no visible divider and it is selectable, sorry

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Don't apologize, you're helping me make the library more robust.  But I do need more of your code to help diagnose the problem.

**Comment by gjenner** [comment]
Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Your html template should create a `contextMenuItem` for each item in the `cmMenuItems` array using `*ngFor`.  Like this:

```html
<context-menu #cmNew>
  <template *ngFor="let action of cmMenuItems" contextMenuItem let-item
    [visible]="action.visible" [enabled]="action.enabled" [divider]="action.divider"
    (execute)="action.execute($event.item)">
    {{ action.html(item) }}
  </template>
</context-menu>
```

**Comment by gjenner** [comment]
This was working great, except the divider, now back to “cannot read property ‘divider’ of undefined

And since it is in HTML, cannot debug easily.  Not a fan of HTML, my last program was Silverlight, loved it

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Do a console.log of your cmMenuItems and check if there’s an item in the array that is null.

**Comment by gjenner** [comment]
Each object is

click: ()

divider: ()

enabled: ()

html: ()

visible: ()

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
Missed part of my previous code behind

if (this.cmMenuItems.length !== 0) {

      this.contextMenuService.show.next({

        // Optional - if unspecified, all context menu components will open

        contextMenu: this.cmNew,

        actions: this.cmMenuItems,

        event: me,

        item: this.objAppointmentSelectedResult,

 

      });

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
This all worked well, except for the divider

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Just remove the `actions` property of the `this.contextMenuService.show` call.  You’re already specifying the actions in the html template.

this.contextMenuService.show.next({
// Optional - if unspecified, all context menu components will open
contextMenu: this.cmNew,
event: me,
item: this.objAppointmentSelectedResult,
});

**Comment by gjenner** [comment]
It would not even display when I did that

I do appreciate your valuable time, but I am going to revert to where I was this morning and revisit it another day, but again, thank you

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Ok.  You’re welcome. Let me know if you want to give it a try again.

**Comment by symbyte** [comment]
I feel like I'm experiencing something similar. Using I'm trying to use the following markup to place a divider in an already existing and functioning context menu: 

```
    <template contextMenuItem divider="true"> </template>
```

At first, I was trying to use the attribute binding syntax (`[divider]="true"`), but was being given the angular template compiler error that `divider` isn't a known property of `template`. I then removed the brackets and am getting an empty, unstyled, anchor tag placed in the menu. 

The rendered output of the divider:
```
<li>
  <a href="">
    <!--template bindings={}--> 
   </a>
</li>
```

and it looks like: 
<img width="202" alt="screen shot 2017-03-26 at 7 27 12 pm" src="https://cloud.githubusercontent.com/assets/6208773/24336786/5b9cc83a-125a-11e7-9dee-2e1f2ac822cb.png">

Any Idea whats going on here?

**Comment by isaacplmann** [comment]
@symbyte using `divider="true"` will set the `divider` property to the string `"true"`.  Using `[divider]="true"` is correct.  You'll get that template compiler error if you forget to include the `contextMenuItem` directive on the `<template>` element.

It should look like this:
```html
<template contextMenuItem [divider]="true"></template>
```

Does that work?

**Comment by symbyte** [comment]
As noted above, I did include the `contextMenuItem` directive on the template element. the error message that angular produces: 
```
zone.js:420 Unhandled Promise rejection: Template parse errors:
Can't bind to 'divider' since it isn't a known property of 'template'. ("
    </template>

    <template contextMenuItem [ERROR ->][divider]="true"></template>

    <template
```

I have, as far as I know, imported the module correctly because everything else works as expected. 

Here is my full context menu section of the template for reference: 
```

  <context-menu #contextMenu>
    <template
        contextMenuItem
        let-item
        (execute)="moveToTop($event)"
      >
      Send {{item?.label}} To Top
    </template>

    <template
        contextMenuItem
        let-item
        (execute)="moveToBottom($event)"
      >
      Send {{item?.label}} To Bottom

    </template>

    <template contextMenuItem [divider]="true"></template>

    <template
        contextMenuItem
        (execute)="showAll($event)"
      >
      Show All
    </template>

    <template
        contextMenuItem
        (execute)="hideAll($event)"
      >
      Hide All
    </template>

  </context-menu>
```

**Comment by isaacplmann** [comment]
Can you double check that you’re using a version of angular2-contextmenu that is greater than 0.6.0?  Sometimes the node_modules folder is out of sync with the package.json and you have to either delete and reinstall or manually check the node_modules/angular2-contextmenu/package.json to see what version number it says.

Your code looks just like the demo code in the repo, so it should work...

**Comment by symbyte** [comment]
Ah yes. We have the library version locked to 0.5.3 because we were getting some strange behavior with where the menu would appear relative to the location of the click. 

It seems that the same behavior is still present in the most recent release, so I'll open an issue on it in the next few days.

**Comment by isaacplmann** [comment]
This issue was moved to isaacplmann/ngx-contextmenu#2
