### ISSUE TITLE
Disabled state does not work with Bootstrap 4

### ISSUE THREAD

**Issue by TrevorBroderick1** [isaacplmann/angular2-contextmenu#6]
The "disabled" class needs to be added to the `<a>` tag rather than the `<li>` tag for the disabled styling to be applied correctly.

This would fix the styling, however you are still able to click the disabled button and perform the click function. Not sure how to fix that one.

**Comment by isaacplmann** [comment]
Items not really being disabled is actually a bug for all the versions of bootstrap.  I'll create a separate issue for it.

**Comment by isaacplmann** [comment]
Fixed in version 1.10
