### ISSUE TITLE
Please move to ng-template to support ng4

### ISSUE THREAD

**Issue by born2net** [isaacplmann/angular2-contextmenu#60]
Please move to ```<ng-template/>``` to support ng4
tx

Sean

**Comment by isaacplmann** [comment]
Yes, thanks for the reminder.  I'll shoot for the end of the week.

**Comment by born2net** [comment]
great tx!

**Comment by isaacplmann** [comment]
Fixed with the rename to ngx-contextmenu.

**Comment by born2net** [comment]
do we need to change anything in the code?

**Comment by isaacplmann** [comment]
Yeah, there are some breaking changes.  See https://github.com/isaacplmann/ngx-contextmenu.  Documentation is a bit sparse now.  I'll try to write more through upgrade steps on Monday.

**Comment by born2net** [comment]
great will look fwd to it.. TX!!!!
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by isaacplmann** [comment]
This issue was moved to isaacplmann/ngx-contextmenu#1
