### ISSUE TITLE
Using 'basicMenu' item click causes navigation to occur

### ISSUE THREAD

**Issue by Sharpiro** [isaacplmann/angular2-contextmenu#62]
When clicking an item in the context menu when using 'basicMenu', navigation occurs.  This means if you are not at the root of your page when right-clicking the context menu item, you will be navigated back to your homepage.

The only way I could workaround this for now was to use the deprecated syntax, which for whatever reason, does not cause this same navigation problem.

For example if I'm using the context menu at ```http://localhost:4200/admin/users``` and I right click a menu item, i will be navigated back to ```http://localhost:4200```.  

Like I said this is not an issue with the deprecated syntax

**Comment by isaacplmann** [comment]
Is this still an issue when using the latest build from `ngx-contextmenu`?

**Comment by Sharpiro** [comment]
Ahh, I didn't realize there was a different repo for that.  Yes, that does look like it works.  Thanks.
