### ISSUE TITLE
Quickly choosing a context menu option will not close the context menu.

### ISSUE THREAD

**Issue by TrevorBroderick1** [isaacplmann/angular2-contextmenu#9]
If you right click to open the context menu and quickly select an option, the option will execute but the menu will remain open.

**Comment by isaacplmann** [comment]
That's because of the solution I put in place for issue #1 .  Basically the context menu can't close for 400 ms after it opens - this is in order to support Firefox on Mac.  If you have an idea for a solution that won't reopen that issue, I'll listen.

**Comment by TrevorBroderick1** [comment]
Interesting.

Is it possible to record if an option is clicked before the time out ends, and then after time out execute the option (if any) that was selected and close the menu?

I don't know what the click event is firing on for the mac issue, depending on that this might be a possible solution.

**Comment by isaacplmann** [comment]
That's true.  I could set up 2 different click listeners.  One for outside clicks that won't do anything for 400 ms and another for item clicks that will close the context menu any time.  That's a good idea.  Removing the won't fix label.

**Comment by isaacplmann** [comment]
Fixed in 0.1.11
